repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
        args: [ '--maxkb=1000' ]
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: [ '--autofix' ]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
